"""add salestable model

Revision ID: 870d81107ab8
Revises: 2aa3e88e1f71
Create Date: 2023-08-25 10:49:43.118042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870d81107ab8'
down_revision: Union[str, None] = '2aa3e88e1f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salestable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('last_update', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salestable')
    # ### end Alembic commands ###
